version: 2

updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Europe/Amsterdam"
    labels:
      - "dependencies"
      - "composer"
    assignees:
      - "maartenpaauw"
    reviewers:
      - "maartenpaauw"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Europe/Amsterdam"
    labels:
      - "dependencies"
      - "github-actions"
    assignees:
      - "maartenpaauw"
    reviewers:
      - "maartenpaauw"
